create extension if not exists "pgcrypto";
create type public.decision_status as enum ('Proposed','Public feedback','Under review','Scheduled for vote','Approved','Rejected','Funded','Implementation','Completed','Delayed');
create table public.decisions (id uuid primary key default gen_random_uuid(),slug text unique not null,title text not null,organization text not null check (organization in ('charlotte','mecklenburg-county','cms')),topic text not null,status public.decision_status not null,summary text not null,why_it_matters text not null,latest_update text not null,next_step text,published_at timestamptz not null default now(),updated_at timestamptz not null default now(),affected_roles text[] not null default '{}',affected_zip_codes text[] not null default '{}',affected_areas text[] not null default '{}',important_dates jsonb not null default '[]',before_text text,after_text text,is_published boolean not null default false);
create table public.sources (id uuid primary key default gen_random_uuid(),decision_id uuid not null references public.decisions(id) on delete cascade,title text not null,organization text not null,url text not null,published_at timestamptz,page_reference text,last_verified_at timestamptz not null default now(),verification_status text not null check (verification_status in ('verified','reviewed','unconfirmed')));
create table public.timeline_events (id uuid primary key default gen_random_uuid(),decision_id uuid not null references public.decisions(id) on delete cascade,date date not null,stage public.decision_status not null,title text not null,description text not null,what_changed text,state text not null check (state in ('completed','current','upcoming','delayed','cancelled')),source_id uuid references public.sources(id) on delete set null,verification_status text not null check (verification_status in ('verified','reviewed','unconfirmed')));
create table public.user_preferences (user_id uuid primary key references auth.users(id) on delete cascade,zip_code text not null,roles text[] not null default '{}',interests text[] not null default '{}',updated_at timestamptz not null default now());
create table public.decision_follows (user_id uuid references auth.users(id) on delete cascade,decision_id uuid references public.decisions(id) on delete cascade,created_at timestamptz not null default now(),primary key(user_id,decision_id));
alter table public.decisions enable row level security;alter table public.sources enable row level security;alter table public.timeline_events enable row level security;alter table public.user_preferences enable row level security;alter table public.decision_follows enable row level security;
create policy "published decisions are public" on public.decisions for select using (is_published);create policy "sources for public decisions are public" on public.sources for select using (exists(select 1 from public.decisions d where d.id=decision_id and d.is_published));create policy "timelines for public decisions are public" on public.timeline_events for select using (exists(select 1 from public.decisions d where d.id=decision_id and d.is_published));create policy "users manage preferences" on public.user_preferences for all using (auth.uid()=user_id) with check(auth.uid()=user_id);create policy "users manage follows" on public.decision_follows for all using (auth.uid()=user_id) with check(auth.uid()=user_id);
